### ISSUE TITLE
5.15.92-dfl  (struct device *)’ from incompatible pointer type ‘int (*)(struct device *)’ [-Werror=incompatible-pointer-types]   .remove  = dfl_bus_remove,

### ISSUE THREAD

**Issue by 208yunyao** [OPAE/linux-dfl-backport#140]
[root@localhost linux-dfl]# sudo make install
sh ./arch/x86/boot/install.sh 5.15.92-dfl \
        arch/x86/boot/bzImage System.map "/boot"
dkms: running auto installation service for kernel 5.15.92-dfl
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/sourc                                         e/dkms.conf)
Deprecated feature: REMAKE_INITRD (/etc/dkms/framework.conf)
Sign command: /lib/modules/5.15.92-dfl/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/sourc                                         e/dkms.conf)

Building module:
Cleaning build area...
make -j112 KERNELRELEASE=5.15.92-dfl KERNELDIR=/lib/modules/5.15.92-dfl/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.15.92-dfl (x86_64)
Consult /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/make.log for more informat                                         ion.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 Failed.
/usr/lib/dracut/dracut.conf.d/90-linux-dfl-backport.conf:omit_drivers+="dfl_pci n5010_hssi n5010_phy s10hss                                         i ptp_dfl_tod intel_m10_bmc_sec_update intel_m10_bmc_hwmon intel_m10_bmc_log intel_m10_bmc_pmci intel_m10_b                                         mc_spi intel_m10_bmc intel_s10_phy qsfp_mem regmap_indirect_register spi_altera_dfl spi_altera_core uio_dfl                                          dfl_emif dfl_n3000_nios dfl_hssi dfl_fme_br dfl_fme_region dfl_fme_mgr dfl_intel_s10_iopll dfl_afu dfl_fme                                          dfl fpga_image_load fpga_region fpga_bridge fpga_mgr regmap_spi_avmm regmap_mmio"

dracut: WARNING: <key>+=" <values> ": <values> should have surrounding white spaces!
dracut: WARNING: This will lead to unwanted side effects! Please fix the configuration file.

[root@localhost linux-dfl]# uname -a
Linux localhost.localdomain 4.18.0-483.el8.x86_64 OFS/linux-dfl#1 SMP Fri Mar 31 13:24:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost linux-dfl]# vim  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/make.log
  CC [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/net/ethernet/silicom/n5010-phy.o
  CC [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/net/ethernet/silicom/n5010-hssi.o
  CC [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl-pci.o
/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl.c:277:54: warning: "RHEL_RELEASE_CODE" is not defined, evaluates to 0 [-Wundef]
 #if LINUX_VERSION_CODE < KERNEL_VERSION(5, 16, 0) && RHEL_RELEASE_CODE < 0x901
                                                      ^~~~~~~~~~~~~~~~~
/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl.c: In function ‘dfl_bus_remove’:
/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl.c:289:54: warning: "RHEL_RELEASE_CODE" is not defined, evaluates to 0 [-Wundef]
 #if LINUX_VERSION_CODE < KERNEL_VERSION(5, 16, 0) && RHEL_RELEASE_CODE < 0x901
                                                      ^~~~~~~~~~~~~~~~~
/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl.c: At top level:
/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl.c:331:13: error: initialization of ‘void (*)(struct device *)’ from incompatible pointer type ‘int (*)(struct device *)’ [-Werror=incompatible-pointer-types]
  .remove  = dfl_bus_remove,
             ^~~~~~~~~~~~~~
/var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/drivers/fpga/dfl.c:331:13: note: (near initialization for ‘dfl_bus_type.remove’)
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-fme-region.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-fme-br.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-hssi.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-emif.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/uio-dfl.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-fme-mgr.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/fpga-region.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/intel-m10-bmc-log.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/intel-m10-bmc-spi.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/intel-m10-bmc-hwmon.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/intel-m10-bmc-pmci.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-intel-s10-iopll.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/spi-altera-dfl.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/fpga-bridge.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/intel-s10-phy.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/fpga-image-load.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/ptp_dfl_tod.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/fpga-mgr.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/regmap-indirect-register.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-fme.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-afu.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-pci.o
  LD [M]  /var/lib/dkms/linux-dfl-backport/0^20220501gsil1.8.r12.gac66976f-1/build/dfl-n3000-nios.o
cc1: some warnings being treated as errors

**Comment by chipb-intel** [comment]
@fpgamatt -- Is this something you can help with?

**Comment by rweight** [comment]
The first concern I see is that both the linux-dfl kernel and the linux-dfl-backport driver are installed. The linux-dfl kernel has the DFL drivers included. Installing the linux-dfl-backport package (which delivers the DFL drivers separately)  on top of that is likely to create confusion, and sometimes unexpected behavior.

If you are OK using the linux-dfl kernel, then my recommendation is to uninstall the linux-dfl-backport package. I think the compilation errors and warnings are all associated with building the linux-dfl-backport dkms driver. Removing the package should clear those errors.

Also note that the latest linux-dfl development is on the fpga-ofs-dev-6.1-lts branch with kernel version 6.1.27.

**Comment by isaacncz** [comment]
@208yunyao i faced the same issue. Do you have the workaround?

**Comment by pcolberg** [comment]
As noted in https://github.com/OFS/linux-dfl-backport/issues/140#issuecomment-2361226582, the primary issue here is a usage error. The [linux-dfl-backport](https://github.com/OFS/linux-dfl-backport) driver should be compiled against the distribution kernel, e.g., the RHEL kernel or the Ubuntu kernel, not the [linux-dfl](https://github.com/OFS/linux-dfl) kernel (which is only intended for development and as a staging tree of the DFL drivers).

The build error against Linux 5.15 due to ["bus: Make remove callback return void"](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=fc7a6209d5710618eb4f72a77cd81b8d694ecf89) had already been resolved in commit 76ed25eb99c37929b1ee426d3393cc8313dc19a8. (@208yunyao was trying to build the older commit ac66976f9fd9e1deaf4c3e3b3e1bccf384e7f341 which was incompatible with Linux 5.15.)
